### ISSUE TITLE
Unable to unlock wauzzzXXXXXXXXXX: invalid literal for int() with base 16: 'zz'

### ISSUE THREAD

**Issue by Rustymage** [audiconnect/audi_connect_ha#116]
After successfully getting this connected, I'm faced with this error when calling the service:

```
service: audiconnect.execute_vehicle_action
data:
  vin: wauzzzXXXXXXXXXX
  action: unlock
```

`Unable to unlock wauzzzXXXXXXXXXX: invalid literal for int() with base 16: 'zz'`

Any help would be appreaciated - I'd be happy to help diagnose with some assistance.

:D
