### ISSUE TITLE
Convert KM to Miles

### ISSUE THREAD

**Issue by leacho73** [audiconnect/audi_connect_ha#158]
Is it possible to convert the default KM into Miles via a setting on the integration?

Although most of Europe use KM for measuring, in the UK we use Miles.

Thanks
Leacho

**Comment by Rustymage** [comment]
```
sensor:
  - platform: template
    sensors:
      oil_distance:
        friendly_name: Odo Miles
        unit_of_measurement: mi
        value_template: >
          {{ (states('sensor.km') | float/1.609 | round) }}
```
Try something like this - I pulled it from here - https://community.home-assistant.io/t/value-template-help-for-a-beginner-to-display-attribute-values-that-are-converted-into-uk-format/55067/3
