### ISSUE TITLE
Cannot change Climatisation state (TFSIe)

### ISSUE THREAD

**Issue by el-Presi** [audiconnect/audi_connect_ha#200]
Hi all!

I can use the integration and see a lot of sensors, but the only thing I can control is the lock-state.
I know, that in ioBroker, you can put on (and off) the climatisation (or preheater) - how is it possible to control this via this integration in HA ?

**Comment by oleg-d** [comment]
I also have this problem, that with this integration there is no climatisation toggle switch. My car is an etron. 

> Hi all!
> 
> I can use the integration and see a lot of sensors, but the only thing I can control is the lock-state. I know, that in ioBroker, you can put on (and off) the climatisation (or preheater) - how is it possible to control this via this integration in HA ?

Try this fork https://github.com/cyr-ius/hass-audiconnect

**Comment by derhappy** [comment]
There is no button generated, you have to call an action like below. I think this is also in the readme somewhere. 

action: call-service
      service: audiconnect.execute_vehicle_action
      service_data:
        vin: wauzzz-putYourVINHere
        action: start_climatisation
      target: {}

**Comment by oleg-d** [comment]
this is how i have it and it works for me, i have put this in my scripts.yaml file

```
audi_service_climatisation:
  sequence:
    - service: audiconnect.execute_vehicle_action
      data:
        vin: <your vin here>
        action: start_climatisation
```

and then have a button that calls this script
```
tap_action:
          action: call-service
          service: script.audi_service_climatisation
```
