### ISSUE TITLE
Feature request :D (total energy consumption)

### ISSUE THREAD

**Issue by devslash0** [audiconnect/audi_connect_ha#258]
How about creating a sensor for total energy consumption? I would love to track energy consumtion in home assistant energy dashboard. Have tried to make my own sensor but without luck. 

If anyone else has done this, please share. But the best would be a feature in this module.

Thanks. Have a nice day!

**Comment by wigster** [comment]
Not sure it's the right place but here is the sensor I have -- it's based on the energy efficiency being reported by the short trip sensor, which now no longer seems to in the API. I have a hybrid, so I do some calculations for EV vs ICE in different modes, so this is a bit more complex than it needs to be.

```yaml
    - name: Smurf total battery consumption
      unique_id: "eryiukesspueorccthuloprth"
      icon: mdi:ev-station
      device_class: energy
      unit_of_measurement: kWh
      state_class: total_increasing
      state: >
        {% set current = this.state |float(0) %}
        {% set increment = 0|float %}
        {% if tripID != 0 %}
        {% set lastTripID = this.attributes.get('last_trip_id',0)%}
        {% set last_batt = this.attributes.get('last_batt_consumed',0)%}
        {% if tripID == lastTripID %}
        {% set increment = batt_consumed - last_batt%}
        {% else %}
        {% set increment = batt_consumed%}
        {%endif%}
        {%endif%}
        {{(current + increment)|round(3)}}
      attributes:
        last_trip_id: >
          {% set lastTripID = this.attributes.get('last_trip_id',0)%}
          {{tripID if (tripID!=0) else lastTripID}}
        last_batt_consumed: >
          {% set lastTripID = this.attributes.get('last_trip_id',0)%}
          {% set last_batt = this.attributes.get('last_batt_consumed',0)%}
          {{batt_consumed if (tripID!=0) else last_batt}}
  trigger:
    - platform: state
      entity_id: sensor.smurf_trip_short_current
      not_to:
        - "unknown"
        - "unavailable"
        - "None"
    - platform: event
      event_type: "SMURF_TRIP"
  action:
    variables:
      tripID: >-
        {%set tripID = state_attr('sensor.smurf_trip_short_current','tripID')%}
        {{tripID if tripID|is_number else 0}}
      is_gas_trip: "{{state_attr('sensor.smurf_trip_short_current','averageFuelConsumption')|float>states('input_number.smurf_ev_trip_threshold')|int}}"
      is_ev_trip: "{{state_attr('sensor.smurf_trip_short_current','averageFuelConsumption')|float<=states('input_number.smurf_ev_trip_threshold')|int}}"
      mileage: "{{state_attr('sensor.smurf_trip_short_current','mileage')|float}}"
      gas_consumed: "{{state_attr('sensor.smurf_trip_short_current','averageFuelConsumption')|float*mileage/100}}"
      batt_consumed: "{{state_attr('sensor.smurf_trip_short_current','averageElectricEngineConsumption')|float*mileage/100}}"
```
