### ISSUE TITLE
Status of audiconnect.execute_vehicle_action  and audiconnect.refresh_vehicle_data services

### ISSUE THREAD

**Issue by DutchKillerbee** [audiconnect/audi_connect_ha#267]
Am I right that the services audiconnect.execute_vehicle_action (start_charger stop_charger) and the audiconnect.refresh_vehicle_data services are not working (yet) after switching to the new API (march 2024)?
Thanks

**Comment by Ingrimmsch93** [comment]
i can not start and stop charging, but refresh is also not working for me. This is an open issue :)

**Comment by t0bias-r** [comment]
same like #262

**Comment by guidokieboom** [comment]
@t0bias-r maybe following helps to find solution. Two days ago audiconnect.execute_vehicle_action start-climatisation worked well for me. This was with the t0bias-r branch. Yesterday when I removed this from HACS, rebooted and installed the arjenvrh branch (f4bf375) it did not work anymore. I used a switch in my configuration.yaml

<img width="328" alt="image" src="https://github.com/arjenvrh/audi_connect_ha/assets/65387179/79d0a254-5134-4d79-8e36-643bf4a2e2c9">


```
switch:
  - platform: template
    switches:
      audiclimatise:
        friendly_name: "Audi Climatisation"
        value_template: "{{ is_state('sensor.audipreheat', 'on') }}"
        turn_on:
          service: audiconnect.execute_vehicle_action
          data:
            vin: wauzzzxxxxxxxxxxx
            action: start_climatisation
        turn_off:
          service: audiconnect.execute_vehicle_action
          data:
            vin: wauzzzxxxxxxxxxxx
            action: start_climatisation
```
