### ISSUE TITLE
Add more actions like turn on climate or charger??

### ISSUE THREAD

**Issue by chillkiller** [audiconnect/audi_connect_ha#64]
Is there a way to add a "climate switch"?

As I know this works on the audi app it should also work on the ha integration, but there is no example or wiki about it...

**Comment by bavala3010** [comment]
You can make automations (or scripts) and use this in the action.
I created a button in HA to immediately start the climatisation and another to start it within 30 minutes.
I even created an automation that sends a message to my phone when I leave the car (= bluetooth connection drops) AND when the outside temperature is below 15 degrees; the message asks if I want to start the climatisation within 30 min of 60 min or....
```
  - service: audiconnect.execute_vehicle_action
    data:
      vin: <your VIN code>
      action: start_climatisation
```
