### ISSUE TITLE
Set climate not working

### ISSUE THREAD

**Issue by rklueber** [audiconnect/audi_connect_ha#74]
Hello,

none of the below works to turn on the climate in my A7 via HA. When I turn it on in the Audi app the status of `sensor.xxx_climatisation_state` changes. But setting it from HA is not working?

Any idea how I can debug this?

Locking/Unlocking the doors works.

````
  audi_service_climatisation:
    sequence:
      - service: audiconnect.execute_vehicle_action
        data:
          vin: !secret vin
          action: 'start_climatisation'

  audi_service_preheater:
    sequence:
      - service: audiconnect.execute_vehicle_action
        data:
          vin: !secret vin
          action: 'start_preheater'

  audi_service_window_heating:
    sequence:
      - service: audiconnect.execute_vehicle_action
        data:
          vin: !secret vin
          action: 'start_window_heating'

````
